baseurl = "https://liangyuanpeng.com/"
title = "Hi,I`m lan"
theme = "hugo-theme-cleanwhite"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
googleAnalytics = "G-RTTRHGYFWL"
preserveTaxonomyNames = true
paginate = 5 #frontpage pagination
hasCJKLanguage = true

[outputs]
home = ["HTML", "RSS", "Algolia"]

[sitemap]
#  changefreq = "monthly"
#  filename = "sitemap.xml"
#  priority = 0.5
   

[params]
  domain = "https://liangyuanpeng.com"
 # header_image = "img/home-bg-jeep.jpg"
 header_image = "https://res.cloudinary.com/lyp/image/upload/v1537619755/hugo/banner/WechatIMG413.jpg"
 SEOTitle = "liangyuanpeng的博客 | liangyuanpeng's Blog"
  description = "lan，工程师⎈, OpenYurt Member,CDF中文本地化SIG成员,开源爱好者 | 公众号:四颗咖啡豆"
  keyword = "liangyuanpeng|LanLiang|OpenYurt|Knative|Pulsar|Prometheus|Halo||边缘计算kubernetes|Docker|CloudNative|Golang|Rust|Istio|微服务"
  #slogan = "路在脚下，心向远方"
 slogan = ""

  image_404 = "img/404-bg.jpg"
  title_404 = "你来到了云原生沙漠 :("

  # leancloud storage for page view counter
  page_view_conter = true
  leancloud_app_id = ""
  leancloud_app_key = ""

  # algolia site search
  algolia_search = true 
  algolia_appId = "VLIE75A81B"
  algolia_indexName = "blog"
  algolia_apiKey = "2aa49a052dc7b70cf63c1f5ebcae8934"

  # Sidebar settings
  sidebar_about_description = "OpenYurt Member|CDF中文本地化SIG成员|CNCF粉丝|Pulsar爱好者|公众号:四颗咖啡豆"
  sidebar_avatar = "https://res.cloudinary.com/lyp/image/upload/v1537624737/hugo/avatar/%E5%93%88%E5%B8%8C%E5%A4%B4%E5%83%8F.jpg"      # use absolute URL, seeing it's used in both `/` and `/about/`

  featured_tags = true 
  featured_condition_size = 2 

  # Baidu Analytics
  ba_track_id = "fad9c137f8ce239f9b323d36c871f8e6"
  
  # We need a proxy to access Disqus api in China
  disqus_proxy = ""
  disqus_site = ""


  [params.social]
  rss            = true 
  email          = "liangyuanpengem@163.com"
  #facebook      = "full profile url in facebook"
  #googleplus    = "full profile url in googleplus"
  twitter       = "https://twitter.com/lan31793328"
  #linkedin       = "full profile url in linkedin"
  #stackoverflow  = "full profile url in stackoverflow"
  #instagram     = "full profile url in instagram"
  github         = "https://github.com/liangyuanpeng"  
  #wechat         = "link of wechat QR code image"
  #pinterest     = "full profile url in pinterest"
  zhihu = "https://www.zhihu.com/people/liangyuanpeng"
  weibo = "https://weibo.com/u/1908782280"
  
 #[[params.friend_link]]
 # title = "Linda的博客"
 # href =  "https://liangyuanpeng.com"

  [[params.bookmark_link]]
 # title =  "Martin Fowler"
 # href =  "https://martinfowler.com"
  [[params.bookmark_link]]
    title = "ServiceMesh中文网"
    href =  "http://www.servicemesh.cn"
  [[params.bookmark_link]]
    title = "Awesome Service Mesh"
    href = "https://servicemesh.gitbooks.io/awesome-servicemesh"
  [[params.bookmark_link]]
 # title =  "Image Compression"
 # href = "https://tinypng.com"
  
[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags"] 


## 配置 utteranc评论,教程参考 https://utteranc.es/
[params.utteranc]
  enable = true
  repo = "liangyuanpeng/liangyuanpeng.github.io" ##换成自己得
  issueTerm = "title"
  theme = "github-light"