
#baseurl = "https://#{baseurl}"
# baseurl = "https://liangyuanpeng.com/"
title = "Hi,I`m lan"
theme = "hugo-theme-cleanwhite"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
googleAnalytics = "RTTRHGYFWL"
preserveTaxonomyNames = true
paginate = 10 #frontpage pagination
hasCJKLanguage = true
#logo = "https://res.cloudinary.com/lyp/image/upload/v1679636162/hash-kube-rs-pulsar.png"


[outputs]
home = ["HTML", "RSS", "Algolia"]

[sitemap]
#  changefreq = "monthly"
#  filename = "sitemap.xml"
#  priority = 0.5
   

[permalinks]
    post = "/:slug"

[params]
  domain = "https://liangyuanpeng.com"
 # header_image = "img/home-bg-jeep.jpg"
 header_image = "/img/banner/art.jpg"
 SEOTitle = "远鹏的博客 | liangyuanpeng's Blog"
  description = "lan，工程师⎈,远鹏|CNCF粉丝|Pulsar爱好者|公众号:四颗咖啡豆|云原生追随者"
  keyword = "liangyuanpeng|LanLiang|OpenYurt|Knative|Pulsar|Prometheus|Halo||边缘计算kubernetes|Docker|CloudNative|Golang|Rust|Istio|微服务"
 slogan = ""
  logo = "/img/aboutme/hash-kube-rs-pulsar.png"

  image_404 = "img/404-bg.jpg"
  title_404 = "你来到了云原生沙漠 :("

  # leancloud storage for page view counter
  page_view_conter = true
  leancloud_app_id = ""
  leancloud_app_key = ""

  # algolia site search
  algolia_search = true 
  algolia_appId = "VLIE75A81B"
  algolia_indexName = "blog"
  algolia_apiKey = "2aa49a052dc7b70cf63c1f5ebcae8934"

  # Sidebar settings
  sidebar_about_description = "⎈⎈远鹏|CNCF粉丝|Pulsar爱好者|公众号:四颗咖啡豆|云原生追随者⎈⎈"
  sidebar_avatar = "/img/aboutme/hash-kube-rs-pulsar.png"      # use absolute URL, seeing it's used in both `/` and `/about/`
  sidebar_wechat = "/img/aboutme/wechat-lan.png"


  featured_tags = true 
  featured_condition_size = 2 

  # Baidu Analytics
  ba_track_id = "fad9c137f8ce239f9b323d36c871f8e6"
  
  # We need a proxy to access Disqus api in China
  disqus_proxy = ""
  disqus_site = ""


  [params.social]
  rss            = true 
  email          = "liangyuanpengem@163.com"
  #facebook      = "full profile url in facebook"
  #googleplus    = "full profile url in googleplus"
  twitter       = "https://twitter.com/lan31793328"
  #linkedin       = "full profile url in linkedin"
  #stackoverflow  = "full profile url in stackoverflow"
  #instagram     = "full profile url in instagram"
  github         = "https://github.com/liangyuanpeng"
  wechat         = "/img/aboutme/wechat-lan.png"
  #pinterest     = "full profile url in pinterest"
  zhihu = "https://www.zhihu.com/people/liangyuanpeng"
  weibo = "https://weibo.com/u/1908782280"

  [[params.bookmark_link]]
    title = "ServiceMesh中文网"
    href =  "http://www.servicemesh.cn"
  [[params.bookmark_link]]
    title = "Awesome Service Mesh"
    href = "https://servicemesh.gitbooks.io/awesome-servicemesh"
  [[params.bookmark_link]]
    title = "KEDA中文化进行中"
    href = "https://keda.liangyuanpeng.com"

   [[params.taglogo]]
    tag = "kubernetes"
    href = "/img/taglogo/emoji_k8s_loft.gif"
  [[params.taglogo]]
    tag = "cncf"
    href = "/img/taglogo/cncf/cncf.png"
  [[params.taglogo]]
    tag = "pipy"
    href = "/img/taglogo/pipy-300.png"
  [[params.taglogo]]
    tag = "kind"
    href = "/img/taglogo/kind.png"
  [[params.taglogo]]
    tag = "chatgpt"
    href = "/img/taglogo/ChatGPT_logo.svg"
  [[params.taglogo]]
    tag = "docker"
    href = "/img/taglogo/docker.png"
  [[params.taglogo]]
    tag = "golang"
    href = "/img/taglogo/golang_mic_drop.png"
  [[params.taglogo]]
    tag = "etcd"
    href = "/img/taglogo/etcd.png"
  [[params.taglogo]]
    tag = "rust"
    href = "/img/taglogo/rust.png"
  [[params.taglogo]]
    tag = "tekton"
    href = "/img/taglogo/tekton.png"
  [[params.taglogo]]
    tag = "knative"
    href = "/img/taglogo/knative.png"
  [[params.taglogo]]
    tag = "envoy"
    href = "/img/taglogo/envoy.png"
  [[params.taglogo]]
    tag = "contour"
    href = "/img/taglogo/contour.png"
  [[params.taglogo]]
    tag = "kubevela"
    href = "/img/taglogo/kubevela.png"
  [[params.taglogo]]
    tag = "prometheus"
    href = "/img/taglogo/prometheus.png"
  [[params.taglogo]]
    tag = "buildpacks"
    href = "/img/taglogo/buildpacks.png"
  [[params.taglogo]]
    tag = "pulsar"
    href = "/img/taglogo/pulsar.png"
  [[params.taglogo]]
    tag = "bookkeeper"
    href = "/img/taglogo/bookkeeper_logo.svg"
  [[params.taglogo]]
    tag = "carvel"
    href = "/img/taglogo/carvel.png"
  [[params.taglogo]]
    tag = "helm"
    href = "/img/taglogo/helm.png"
  [[params.taglogo]]
    tag = "openkruise"
    href = "/img/taglogo/openkruise.png"
  [[params.taglogo]]
    tag = "shipwright"
    href = "/img/taglogo/shipwright.png"
  [[params.taglogo]]
    tag = "longhorn"
    href = "/img/taglogo/longhorn.png"
  [[params.taglogo]]
    tag = "opa"
    href = "/img/taglogo/opa.png"
  [[params.taglogo]]
    tag = "grpc"
    href = "/img/taglogo/grpc.png"
  [[params.taglogo]]
    tag = "cloudevents"
    href = "/img/taglogo/cloudevents.png"
  [[params.taglogo]]
    tag = "oras"
    href = "/img/taglogo/cncf/oras/oras-horizontal-color.png"
  [[params.taglogo]]
    tag = "istio"
    href = "/img/taglogo/cncf/istio/istio-icon-color.png"
  [[params.taglogo]]
    tag = "karmada"
    href = "/img/taglogo/cncf/karmada/karmada-icon-color.png"


[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags"] 


## 配置 utteranc 评论,教程参考 https://utteranc.es/
[params.utteranc]
  enable = false
  repo = "liangyuanpeng/liangyuanpeng.github.io" ##换成自己的
  issueTerm = "title"
  theme = "github-light"


## 配置 giscus 评论,教程参考 https://utteranc.es/
[params.giscus]
  enable = true
  repo = "liangyuanpeng/liangyuanpeng.github.io" ##换成自己的
  repoid = "MDEwOlJlcG9zaXRvcnkxNDkwMDQ2OTM="
  category = "comments"
  categoryid = "DIC_kwDOCOGhlc4CVwo2"
  mapping = "title"
  theme = "light"